### ISSUE TITLE
No such service: tinkerwell

### ISSUE THREAD

**Issue by CallumEddisford** [tjespers/tinkerwell-interpreters#2]
Hi @tjespers,

Just a quick note - in the examples, the service name in `cli.interpreter` differs from that in the `docker-compose.yaml`

https://github.com/tjespers/tinkerwell-interpreters/blob/54dd143ab2843ba89f0786e8d88b658044bb2c4e/examples/docker-compose/cli.interpreter#L18

https://github.com/tjespers/tinkerwell-interpreters/blob/54dd143ab2843ba89f0786e8d88b658044bb2c4e/examples/docker-compose/docker-compose.yaml#L5

Great work on this by the way!

**Comment by tjespers** [comment]
@CallumEddisford thanks for pointing that one out! Will fix that one right away.
